services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_rest_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6380:6379"
#      - host-port:container-port(6379)
    volumes:
      - ./data/redis:/data

volumes:
  postgres_data:
  redis_data: