spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_rest_postgres
    username: user
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
  data:
    redis:
      port: 6380
      host: localhost
      password:
server:
  port: 8080